/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v2 "tkestack.io/tke/api/platform/v2"
)

// FakeCronHPAs implements CronHPAInterface
type FakeCronHPAs struct {
	Fake *FakePlatformV2
}

var cronhpasResource = schema.GroupVersionResource{Group: "platform.tkestack.io", Version: "v2", Resource: "cronhpas"}

var cronhpasKind = schema.GroupVersionKind{Group: "platform.tkestack.io", Version: "v2", Kind: "CronHPA"}

// Get takes name of the cronHPA, and returns the corresponding cronHPA object, and an error if there is any.
func (c *FakeCronHPAs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(cronhpasResource, name), &v2.CronHPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.CronHPA), err
}

// List takes label and field selectors, and returns the list of CronHPAs that match those selectors.
func (c *FakeCronHPAs) List(ctx context.Context, opts v1.ListOptions) (result *v2.CronHPAList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(cronhpasResource, cronhpasKind, opts), &v2.CronHPAList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2.CronHPAList{ListMeta: obj.(*v2.CronHPAList).ListMeta}
	for _, item := range obj.(*v2.CronHPAList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cronHPAs.
func (c *FakeCronHPAs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(cronhpasResource, opts))
}

// Create takes the representation of a cronHPA and creates it.  Returns the server's representation of the cronHPA, and an error, if there is any.
func (c *FakeCronHPAs) Create(ctx context.Context, cronHPA *v2.CronHPA, opts v1.CreateOptions) (result *v2.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(cronhpasResource, cronHPA), &v2.CronHPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.CronHPA), err
}

// Update takes the representation of a cronHPA and updates it. Returns the server's representation of the cronHPA, and an error, if there is any.
func (c *FakeCronHPAs) Update(ctx context.Context, cronHPA *v2.CronHPA, opts v1.UpdateOptions) (result *v2.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(cronhpasResource, cronHPA), &v2.CronHPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.CronHPA), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCronHPAs) UpdateStatus(ctx context.Context, cronHPA *v2.CronHPA, opts v1.UpdateOptions) (*v2.CronHPA, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(cronhpasResource, "status", cronHPA), &v2.CronHPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.CronHPA), err
}

// Delete takes name of the cronHPA and deletes it. Returns an error if one occurs.
func (c *FakeCronHPAs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(cronhpasResource, name), &v2.CronHPA{})
	return err
}

// Patch applies the patch and returns the patched cronHPA.
func (c *FakeCronHPAs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.CronHPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(cronhpasResource, name, pt, data, subresources...), &v2.CronHPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v2.CronHPA), err
}
