/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2020 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v2 "tkestack.io/tke/api/client/clientset/versioned/typed/platform/v2"
)

type FakePlatformV2 struct {
	*testing.Fake
}

func (c *FakePlatformV2) CSIOperators() v2.CSIOperatorInterface {
	return &FakeCSIOperators{c}
}

func (c *FakePlatformV2) Clusters() v2.ClusterInterface {
	return &FakeClusters{c}
}

func (c *FakePlatformV2) ClusterAddons() v2.ClusterAddonInterface {
	return &FakeClusterAddons{c}
}

func (c *FakePlatformV2) ClusterAddonTypes() v2.ClusterAddonTypeInterface {
	return &FakeClusterAddonTypes{c}
}

func (c *FakePlatformV2) ClusterCredentials() v2.ClusterCredentialInterface {
	return &FakeClusterCredentials{c}
}

func (c *FakePlatformV2) ClusterGroupAPIResourceItemses() v2.ClusterGroupAPIResourceItemsInterface {
	return &FakeClusterGroupAPIResourceItemses{c}
}

func (c *FakePlatformV2) ConfigMaps() v2.ConfigMapInterface {
	return &FakeConfigMaps{c}
}

func (c *FakePlatformV2) CronHPAs() v2.CronHPAInterface {
	return &FakeCronHPAs{c}
}

func (c *FakePlatformV2) Machines() v2.MachineInterface {
	return &FakeMachines{c}
}

func (c *FakePlatformV2) PersistentEvents() v2.PersistentEventInterface {
	return &FakePersistentEvents{c}
}

func (c *FakePlatformV2) Registries() v2.RegistryInterface {
	return &FakeRegistries{c}
}

func (c *FakePlatformV2) TappControllers() v2.TappControllerInterface {
	return &FakeTappControllers{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePlatformV2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
